services:

  db:
    image: postgres:15-alpine
    container_name: gym-postgres-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: gym_db
      POSTGRES_USER: gym_user
      POSTGRES_PASSWORD: 1234
    volumes:
      - gym-db-storage:/var/lib/postgresql/data
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: gym-spring-app
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/gym_db
      spring.datasource.username: gym_user
      spring.datasource.password: 1234
    depends_on:
      - db

volumes:
  gym-db-storage: