services:
  db-test:
    image: postgres:15-alpine
    container_name: gym-postgres-TEST
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: gym_db
      POSTGRES_USER: gym_user
      POSTGRES_PASSWORD: 1234567890
    volumes:
      - test-data-volume:/var/lib/postgresql/data
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  test-data-volume: